linux: Add Upstream-Status in kernel patch
Now it's mandatory to specify the Upstream-Status in
any patch from any meta-layer.

linux-yocto-6.1.62+git-r0 do_patch: QA Issue: Missing Upstream-Status in patch
ERROR: linux-yocto-6.1.62+git-r0 do_patch: Fatal QA errors were found, failing task.

Signed-off-by: Daniel Dragomir <daniel1x.dragomir@intel.com>