linux-yocto-debug: Fix missing patch from poky
For the debug version of the linux-yocto kernel we have a .bb recipe
which requires the linux-yocto.inc from poky layer. So, it inherit
patches from poky mentioned in SRC_URI but doesn't get the paths to
seach files from SRC_URI since it's a .bb recipe (a .bbappend one
inherits also the paths of the original .bb recipe).

To fix this and help bitbake to find the files from SRC_URI we can
extend the paths to be searched via FILESEXTRAPATHS variable.

ERROR: meta-intel-srp/recipes-kernel/linux/linux-yocto-debug_6.1.bb:
   Unable to get checksum for linux-yocto-upstream SRC_URI entry
   0001-perf-cpumap-Make-counter-as-unsigned-ints.patch: file could
   not be found

Signed-off-by: Daniel Dragomir <daniel1x.dragomir@intel.com>